### ISSUE TITLE
Explain me please this error: Licence Error

### ISSUE THREAD

**Issue by yerassylnurlanov** [blinkcard/blinkcard-in-browser#17]
Error init sdk: {message: Internal Error( server permission expired), code: LICENCE_UNLOCK_ERROR, details: Permission expired .
What does it mean? 
Device : Realme c25y
Android version: 11
Browser : Chrome last version

**Comment by AngTim** [comment]
Hello Yerassyl,

Thank you for the inquiry; since you have also reached out to our support e-mail, we will close the issue here on GitHub and continue the conversation via e-mail.
Thank you for your understanding.

Kind regards,
Angelo

**Comment by vjekoart** [comment]
We are closing this issue since communication has been transferred to the official support e-mail.
