### ISSUE TITLE
Explain me this error: Problem during initialization of worker file

### ISSUE THREAD

**Issue by yerassylnurlanov** [blinkcard/blinkcard-in-browser#20]
Log shows: Error initialization of sdk : "Problem during initialization of worker file" . Also on second try it works, then on third try it shows: Error initialization of sdk: {message: Failed to load WASM in web worker!, code: WORKER_WASM_LOAD_FAILURE, details:{} }, Could someone explain what is the problem? THANK U IN ADVANCE

**Comment by AngTim** [comment]
Hello Yerassyl,

Thank you for the inquiry; since you have also reached out to our support e-mail, we will close the issue here on GitHub and continue the conversation via e-mail.
I appreciate your understanding.

Kind regards,
Angelo

**Comment by vjekoart** [comment]
We are closing this issue since communication has been transferred to the official support e-mail.
